# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolator_0/system_fir_interpolator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_interpolator_0 || ORIG_REF_NAME==system_fir_interpolator_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolator_0/util_fir_int.srcs/sources_1/ip/fir_interp/fir_interp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_interp || ORIG_REF_NAME==fir_interp} -quiet] -quiet

# IP: bd/system/ip/system_interp_slice_0/system_interp_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_interp_slice_0 || ORIG_REF_NAME==system_interp_slice_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimator_0/system_fir_decimator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_decimator_0 || ORIG_REF_NAME==system_fir_decimator_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimator_0/util_fir_dec.srcs/sources_1/ip/fir_decim/fir_decim.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_decim || ORIG_REF_NAME==fir_decim} -quiet] -quiet

# IP: bd/system/ip/system_decim_slice_0/system_decim_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_decim_slice_0 || ORIG_REF_NAME==system_decim_slice_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_16_0/system_GND_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_16_0 || ORIG_REF_NAME==system_GND_16_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp1_interconnect_0/system_axi_hp1_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp1_interconnect_0 || ORIG_REF_NAME==system_axi_hp1_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axis2Complex_0/system_axis2Complex_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis2Complex_0 || ORIG_REF_NAME==system_axis2Complex_0} -quiet] -quiet

# IP: bd/system/ip/system_duppl_0/system_duppl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_duppl_0 || ORIG_REF_NAME==system_duppl_0} -quiet] -quiet

# IP: bd/system/ip/system_nco_0/system_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_nco_0 || ORIG_REF_NAME==system_nco_0} -quiet] -quiet

# IP: bd/system/ip/system_mixer_0/system_mixer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mixer_0 || ORIG_REF_NAME==system_mixer_0} -quiet] -quiet

# IP: bd/system/ip/system_use_nco_0/system_use_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_use_nco_0 || ORIG_REF_NAME==system_use_nco_0} -quiet] -quiet

# IP: bd/system/ip/system_cplx_to_axis_0/system_cplx_to_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cplx_to_axis_0 || ORIG_REF_NAME==system_cplx_to_axis_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_clk_x_0/system_fifo_clk_x_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_clk_x_0 || ORIG_REF_NAME==system_fifo_clk_x_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo2Cplx_0/system_fifo2Cplx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo2Cplx_0 || ORIG_REF_NAME==system_fifo2Cplx_0} -quiet] -quiet

# IP: bd/system/ip/system_duppl_xcorr_0/system_duppl_xcorr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_duppl_xcorr_0 || ORIG_REF_NAME==system_duppl_xcorr_0} -quiet] -quiet

# IP: bd/system/ip/system_prn1_gen_0/system_prn1_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_prn1_gen_0 || ORIG_REF_NAME==system_prn1_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_prn4_gen_0/system_prn4_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_prn4_gen_0 || ORIG_REF_NAME==system_prn4_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_xcorr1_0/system_xcorr1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xcorr1_0 || ORIG_REF_NAME==system_xcorr1_0} -quiet] -quiet

# IP: bd/system/ip/system_xcorr4_0/system_xcorr4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xcorr4_0 || ORIG_REF_NAME==system_xcorr4_0} -quiet] -quiet

# IP: bd/system/ip/system_data_to_ram_0/system_data_to_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_to_ram_0 || ORIG_REF_NAME==system_data_to_ram_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_xfer_status_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status} -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/ad_rst_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl} -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_interpolator_0/util_fir_int.srcs/sources_1/ip/fir_interp/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_interp || ORIG_REF_NAME==fir_interp} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_decimator_0/util_fir_dec.srcs/sources_1/ip/fir_decim/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_decim || ORIG_REF_NAME==fir_decim} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_nco_0/nco_counter.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_nco_0 || ORIG_REF_NAME==system_nco_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_use_nco_0/switchComplex.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_use_nco_0 || ORIG_REF_NAME==system_use_nco_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fifo_clk_x_0/system_fifo_clk_x_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_clk_x_0 || ORIG_REF_NAME==system_fifo_clk_x_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fifo_clk_x_0/system_fifo_clk_x_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_clk_x_0 || ORIG_REF_NAME==system_fifo_clk_x_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_xcorr1_0/xcorr_prn_slow_complex.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_xcorr1_0 || ORIG_REF_NAME==system_xcorr1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_xcorr4_0/xcorr_prn_slow_complex.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_xcorr4_0 || ORIG_REF_NAME==system_xcorr4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_data_to_ram_0/dataComplex_to_ram.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_data_to_ram_0 || ORIG_REF_NAME==system_data_to_ram_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc

# XDC: /home/jmfriedt/xilinx/oscimpDigital/doc/tutorials/plutosdr/3-PRN_on_PL/design/system_constr.xdc
