all: 1-adalmPluto_within_OscimpDigital.pdf

1-adalmPluto_within_OscimpDigital.pdf: 1-adalmPluto_within_OscimpDigital.tex
	pdflatex $^
	pdflatex $^

clean:
	rm *.log *.aux  *.out *bak 1-adalmPluto_within_OscimpDigital.pdf
