all: 2-adalmPluto_within_OscimpDigital.pdf

2-adalmPluto_within_OscimpDigital.pdf: 2-adalmPluto_within_OscimpDigital.tex
	pdflatex $^
	pdflatex $^

clean:
	rm *.log *.aux  *.out *bak 2-adalmPluto_within_OscimpDigital.pdf
