set_property SRC_FILE_INFO {cfile:/home/jmfriedt/xilinx/oscimpDigital/doc/tutorials/plutosdr/3-PRN_on_PL/design/system_constr.xdc rfile:../../../system_constr.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jmfriedt/xilinx/oscimpDigital/doc/tutorials/plutosdr/3-PRN_on_PL/design/pluto.srcs/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc rfile:../../../pluto.srcs/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc id:2 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9361_dac_dma/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jmfriedt/xilinx/oscimpDigital/doc/tutorials/plutosdr/3-PRN_on_PL/design/pluto.srcs/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc rfile:../../../pluto.srcs/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc id:3 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9361_adc_dma/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/sdb2/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../../mnt/sdb2/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:4 order:LATE scoped_inst:i_system_wrapper/system_i/fifo_clk_x/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/sdb2/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../../mnt/sdb2/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:5 order:LATE scoped_inst:i_system_wrapper/system_i/fifo_clk_x/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L12  IOSTANDARD LVCMOS18 } [get_ports rx_clk_in]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N13  IOSTANDARD LVCMOS18 } [get_ports rx_frame_in]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H14  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[0]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J13  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[1]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  G14  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[2]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H13  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[3]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  G12  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[4]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H12  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[5]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  G11  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[6]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J14  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[7]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J15  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[8]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  K15  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[9]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H11  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[10]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J11  IOSTANDARD LVCMOS18 } [get_ports rx_data_in[11]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P10  IOSTANDARD LVCMOS18} [get_ports tx_clk_out]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L14  IOSTANDARD LVCMOS18} [get_ports tx_frame_out]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P15  IOSTANDARD LVCMOS18} [get_ports tx_data_out[0]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R13  IOSTANDARD LVCMOS18} [get_ports tx_data_out[1]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R15  IOSTANDARD LVCMOS18} [get_ports tx_data_out[2]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P11  IOSTANDARD LVCMOS18} [get_ports tx_data_out[3]]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R11  IOSTANDARD LVCMOS18} [get_ports tx_data_out[4]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R12  IOSTANDARD LVCMOS18} [get_ports tx_data_out[5]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P14  IOSTANDARD LVCMOS18} [get_ports tx_data_out[6]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P13  IOSTANDARD LVCMOS18} [get_ports tx_data_out[7]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N9   IOSTANDARD LVCMOS18} [get_ports tx_data_out[8]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  M9   IOSTANDARD LVCMOS18} [get_ports tx_data_out[9]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R8   IOSTANDARD LVCMOS18} [get_ports tx_data_out[10]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R7   IOSTANDARD LVCMOS18} [get_ports tx_data_out[11]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L15  IOSTANDARD LVCMOS18} [get_ports gpio_status[0]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  M15  IOSTANDARD LVCMOS18} [get_ports gpio_status[1]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N11  IOSTANDARD LVCMOS18} [get_ports gpio_status[2]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N12  IOSTANDARD LVCMOS18} [get_ports gpio_status[3]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  M10  IOSTANDARD LVCMOS18} [get_ports gpio_status[4]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  M11  IOSTANDARD LVCMOS18} [get_ports gpio_status[5]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N7   IOSTANDARD LVCMOS18} [get_ports gpio_status[6]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N8   IOSTANDARD LVCMOS18} [get_ports gpio_status[7]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  F13  IOSTANDARD LVCMOS18} [get_ports gpio_ctl[0]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  F14  IOSTANDARD LVCMOS18} [get_ports gpio_ctl[1]]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  G15  IOSTANDARD LVCMOS18} [get_ports gpio_ctl[2]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  F15  IOSTANDARD LVCMOS18} [get_ports gpio_ctl[3]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L13  IOSTANDARD LVCMOS18} [get_ports gpio_en_agc]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P9   IOSTANDARD LVCMOS18} [get_ports gpio_resetb]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  K12  IOSTANDARD LVCMOS18} [get_ports enable]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  K11  IOSTANDARD LVCMOS18} [get_ports txnrx]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  M14  IOSTANDARD LVCMOS18 PULLTYPE PULLUP} [get_ports iic_scl]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N14  IOSTANDARD LVCMOS18 PULLTYPE PULLUP} [get_ports iic_sda]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  E12  IOSTANDARD LVCMOS18  PULLTYPE PULLUP} [get_ports spi_csn]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  E11  IOSTANDARD LVCMOS18} [get_ports spi_clk]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  E13  IOSTANDARD LVCMOS18} [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  F12  IOSTANDARD LVCMOS18} [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  K13  IOSTANDARD LVCMOS18} [get_ports gpio_bd]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P8   IOSTANDARD LVCMOS18} [get_ports clk_out]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  M12  IOSTANDARD LVCMOS18} [get_ports cos_fake_o]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.15
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D8   PULLTYPE PULLUP} [get_ports fixed_io_mio[ 0]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A5   PULLTYPE PULLUP} [get_ports fixed_io_mio[ 1]]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A8                  } [get_ports fixed_io_mio[ 2]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A7                  } [get_ports fixed_io_mio[ 3]]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C8                  } [get_ports fixed_io_mio[ 4]]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A9                  } [get_ports fixed_io_mio[ 5]]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A10                 } [get_ports fixed_io_mio[ 6]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D9                  } [get_ports fixed_io_mio[ 7]]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B6                  } [get_ports fixed_io_mio[ 8]]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B5   PULLTYPE PULLUP} [get_ports fixed_io_mio[ 9]]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D6   PULLTYPE PULLUP} [get_ports fixed_io_mio[10]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B10  PULLTYPE PULLUP} [get_ports fixed_io_mio[11]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B7   PULLTYPE PULLUP} [get_ports fixed_io_mio[12]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C6   PULLTYPE PULLUP} [get_ports fixed_io_mio[13]]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B9   PULLTYPE PULLUP} [get_ports fixed_io_mio[14]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D10  PULLTYPE PULLUP} [get_ports fixed_io_mio[15]]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A15  PULLTYPE PULLUP} [get_ports fixed_io_mio[16]]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D11  PULLTYPE PULLUP} [get_ports fixed_io_mio[17]]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B15  PULLTYPE PULLUP} [get_ports fixed_io_mio[18]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C12  PULLTYPE PULLUP} [get_ports fixed_io_mio[19]]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E15  PULLTYPE PULLUP} [get_ports fixed_io_mio[20]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C11  PULLTYPE PULLUP} [get_ports fixed_io_mio[21]]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D15  PULLTYPE PULLUP} [get_ports fixed_io_mio[22]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A14  PULLTYPE PULLUP} [get_ports fixed_io_mio[23]]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B14  PULLTYPE PULLUP} [get_ports fixed_io_mio[24]]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C14  PULLTYPE PULLUP} [get_ports fixed_io_mio[25]]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A13  PULLTYPE PULLUP} [get_ports fixed_io_mio[26]]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D14  PULLTYPE PULLUP} [get_ports fixed_io_mio[27]]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B12  PULLTYPE PULLUP} [get_ports fixed_io_mio[28]]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D13  PULLTYPE PULLUP} [get_ports fixed_io_mio[29]]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A12  PULLTYPE PULLUP} [get_ports fixed_io_mio[30]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C13  PULLTYPE PULLUP} [get_ports fixed_io_mio[31]]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports fixed_io_ps_clk]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C9 [get_ports fixed_io_ps_porb]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H3 [get_ports fixed_io_ddr_vrp]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports fixed_io_ddr_vrn]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N3 [get_ports ddr_ck_p]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports ddr_ck_n]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports ddr_addr[0]]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports ddr_addr[1]]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports ddr_addr[2]]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports ddr_addr[3]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports ddr_addr[4]]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports ddr_addr[5]]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports ddr_addr[6]]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M5 [get_ports ddr_addr[7]]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports ddr_addr[8]]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports ddr_addr[9]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports ddr_addr[10]]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports ddr_addr[11]]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports ddr_addr[12]]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports ddr_addr[13]]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports ddr_addr[14]]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports ddr_ba[0]]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports ddr_ba[1]]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports ddr_ba[2]]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports ddr_reset_n]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports ddr_cs_n]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports ddr_ras_n]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports ddr_cas_n]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports ddr_we_n]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports ddr_cke]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports ddr_odt]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports ddr_dq[0]]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports ddr_dq[1]]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports ddr_dq[2]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports ddr_dq[3]]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports ddr_dq[4]]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports ddr_dq[5]]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports ddr_dq[6]]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports ddr_dq[7]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports ddr_dq[8]]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports ddr_dq[9]]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports ddr_dq[10]]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports ddr_dq[11]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports ddr_dq[12]]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports ddr_dq[13]]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports ddr_dq[14]]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports ddr_dq[15]]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1 [get_ports ddr_dm[0]]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports ddr_dm[1]]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports ddr_dqs_p[0]]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2 [get_ports ddr_dqs_n[0]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports ddr_dqs_p[1]]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports ddr_dqs_n[1]]
current_instance i_system_wrapper/system_i/axi_ad9361_dac_dma/inst
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_req_response_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_response_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_dest_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_dest_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_src_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier -filter {IS_SEQUENTIAL && NAME =~ *i_store_and_forward/burst_len_mem_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_dest_bl_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_dest_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
current_instance
current_instance i_system_wrapper/system_i/axi_ad9361_adc_dma/inst
set_property src_info {type:SCOPED_XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_src_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_src_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_rewind_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_rewind_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_rewind_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_dest_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_dest_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_src_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier -filter {IS_SEQUENTIAL && NAME =~ *i_store_and_forward/burst_len_mem_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_dest_bl_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_dest_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
current_instance
current_instance i_system_wrapper/system_i/fifo_clk_x/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:4 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/fifo_clk_x/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:5 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
